name: ''
description: ''
inputs:
  force_bun:
    description: ''
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Retrieve dependency cache
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('bun.lockb') }}
        restore-keys: node_modules-
    - name: Set up Bun
      if: steps.cache.outputs.cache-hit != 'true' || inputs.force_bun == 'true'
      uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: bun install
      shell: bash